In [1]:
import pandas as pd
import numpy as np
from scipy import sparse
from scipy.sparse.linalg import norm

In [2]:
movies = pd.read_csv('ml-latest-small/movies.csv')
tags = pd.read_csv('ml-latest-small/tags.csv')
ratings = pd.read_csv('ml-latest-small/ratings.csv')
links = pd.read_csv('ml-latest-small/links.csv')

In [ ]:
movies.head(5)

In [ ]:
tags.head(5)

In [52]:
ratings.head(5)
movie_sum_score = ratings.groupby('movieId').sum()
movie_sum_score[movie_sum_score.rating == 0]
movies

movieId                                              title  \
0           1                                   Toy Story (1995)   
1           2                                     Jumanji (1995)   
2           3                            Grumpier Old Men (1995)   
3           4                           Waiting to Exhale (1995)   
4           5                 Father of the Bride Part II (1995)   
5           6                                        Heat (1995)   
6           7                                     Sabrina (1995)   
7           8                                Tom and Huck (1995)   
8           9                                Sudden Death (1995)   
9          10                                   GoldenEye (1995)   
10         11                     American President, The (1995)   
11         12                 Dracula: Dead and Loving It (1995)   
12         13                                       Balto (1995)   
13         14                                       Nixon (1995)   
14         15                            Cutthroat Island (1995)   
15         16                                      Casino (1995)   
16         17                       Sense and Sensibility (1995)   
17         18                                  Four Rooms (1995)   
18         19              Ace Ventura: When Nature Calls (1995)   
19         20                                 Money Train (1995)   
20         21                                  Get Shorty (1995)   
21         22                                     Copycat (1995)   
22         23                                   Assassins (1995)   
23         24                                      Powder (1995)   
24         25                           Leaving Las Vegas (1995)   
25         26                                     Othello (1995)   
26         27                                Now and Then (1995)   
27         28                                  Persuasion (1995)   
28         29  City of Lost Children, The (Cité des enfants p...   
29         30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
...       ...                                                ...   
9095   159690  Teenage Mutant Ninja Turtles: Out of the Shado...   
9096   159755          Popstar: Never Stop Never Stopping (2016)   
9097   159858                             The Conjuring 2 (2016)   
9098   159972                     Approaching the Unknown (2016)   
9099   160080                                Ghostbusters (2016)   
9100   160271                        Central Intelligence (2016)   
9101   160438                                Jason Bourne (2016)   
9102   160440                             The Maid's Room (2014)   
9103   160563                        The Legend of Tarzan (2016)   
9104   160565                    The Purge: Election Year (2016)   
9105   160567              Mike & Dave Need Wedding Dates (2016)   
9106   160590                         Survive and Advance (2013)   
9107   160656                                    Tallulah (2016)   
9108   160718                                       Piper (2016)   
9109   160954                                       Nerve (2016)   
9110   161084                       My Friend Rockefeller (2015)   
9111   161155                                   Sunspring (2016)   
9112   161336                  Author: The JT LeRoy Story (2016)   
9113   161582                          Hell or High Water (2016)   
9114   161594               Kingsglaive: Final Fantasy XV (2016)   
9115   161830                                        Body (2015)   
9116   161918                Sharknado 4: The 4th Awakens (2016)   
9117   161944              The Last Brickmaker in America (2001)   
9118   162376                                    Stranger Things   
9119   162542                                      Rustom (2016)   
9120   162672                                Mohenjo Daro (2016)   
9121   163056                               Shin Godzilla (201

In [3]:
# user_movie rating matrix
user_movie = sparse.coo_matrix((ratings.rating, (ratings.userId, ratings.movieId)))
movie_user = user_movie.transpose()

In [ ]:
# build user to user similarity matrix
def user2user_fast(ratings, user_movie):
    # create a matrix that represent user similarity
    nusers = ratings.userId.max()  # user id starts from 1
    user_similarity = np.ones((nusers+1, nusers+1))
    user_movie = user_movie.tocsc()
    
    # dot products
    inner = user_movie * user_movie.transpose()
    norms = np.sqrt(inner.diagonal())
    
    # compute similarity between user i, j
    count = 0
    for i in range(1, nusers):
        coli = inner.getcol(i)
        for j in range(i+1, nusers):
            # col[i][j] is the dot b/t user i, j
            numerator = coli[j].toarray()[0][0]
            denom = norms[i] * norms[j]
            user_similarity[i][j] = user_similarity[j][i] = numerator / denom
            
            count += 1
            if (count % 10001 == 0):
                print("{} and {} sim: {}".format(i, j, user_similarity[i][j]))
            
    return user_similarity 

In [ ]:
user_similarity = user2user_fast(ratings)

In [ ]:
np.save('user_similarity.npy', user_similarity)

In [ ]:
# query top k similar items from top N users
def getUserRec(userid, user_movie, user_similarity, N=10, k=10):
    # get top N similar users
    similar_users = user_similarity[userid, :]
    # exclude index=0 and index=userid
    similar_users[0] = similar_users[userid] = -1
    topn_index = np.argsort(similar_users)[::-1][:N] # [::-1] reverse to descending order
    topn_similarity = sparse.lil_matrix(similar_users[topn_index])
    
    # compute the weighted average for items rated by the topN users
    user_movie = user_movie.tolil() # for slicing
    topn_ratings = user_movie[topn_index, :]
    topn_movie_scores = topn_ratings.multiply(topn_similarity.transpose())
    weighted_scores = np.array(topn_movie_scores.sum(axis=0)).flatten()
    
    # return the top K movies that the users have not rated
    user_watched_indices = user_movie[userid, :].nonzero()[1]
    weighted_scores[user_watched_indices] = 0
    topk_index = np.argsort(weighted_scores)[::-1][:k]
    
    return topk_index

In [ ]:
# TODO: sort favorites generes for each user
userId = 400
movie_liked = ratings[ratings.userId == userId].movieId
movie_liked_names = movies[movies.movieId.isin(movie_liked)]
movie_liked_names.head(10)

In [ ]:
topk = getUserRec(userId, user_movie, user_similarity)
movie_names = movies[movies.movieId.isin(topk)]
movie_names

In [23]:
# build user to user similarity 
# this generalize the user2user_fast above
# @param rating_matrix: rating_matrix[i][j] is user i rating to movie j
def compute_similarity(rating_matrix):
    # create a matrix that represent row similarity
    (N, M) = rating_matrix.shape # row/col index starts from 1
    print("Shape=", N, M)
    #row_similarity = np.ones((N+1, N+1))
    rating_matrix = rating_matrix.tocsc()
    
    # dot products
    print("dot product")
    dots = rating_matrix * rating_matrix.transpose()
    norms = np.sqrt(dots.diagonal())
    #print(norms.shape, norms.nonzero()[0].shape)
    norms[norms == 0.0] = 1.0 # fill missing values
    norms = norms.reshape((N, 1))
    norms = sparse.csc_matrix(norms)
    denom = norms * norms.transpose()
    
    print("dots", type(dots), "denom", type(denom))
    #row_similarity = dots / denom
    print("return")
    return (dots, denom)
    #return row_similarity 

In [24]:
# compute_similarity(user_movie) computes the user similarity
(dots, denom) = compute_similarity(movie_user)

Shape= 163950 672
dot product
(163950,) (9066,)
dots <class 'scipy.sparse.csc.csc_matrix'> denom <class 'scipy.sparse.csc.csc_matrix'>
return


In [30]:
dots = movie_user*movie_user.transpose()

In [ ]:
# there are some movieIds not used, and therefore they should be treated as "dummy"
(N, M) = movie_user.shape
norms = np.sqrt(dots.diagonal())
norms[norms == 0.0] = 1.0
norms = norms.reshape((N, 1))
norms = sparse.csc_matrix(norms)
denom = norms * norms.transpose()

In [10]:
a=np.array(range(1,6))
print(a)
a=a.reshape((5, 1))
print(a.shape)
m=a * a.transpose()
n=np.diag(m.diagonal())
n

[1 2 3 4 5]
(5, 1)


array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [11]:
m = 2*np.ones((5, 5))
print(n)
print(m)
n/m

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


array([[  0.5,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   2. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   4.5,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   8. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5]])

In [ ]:
n.non